### ISSUE TITLE
[MacOS] App icon not shown on executable 

### ISSUE THREAD

**Issue by dan0v** [dan0v/xdelta3-cross-gui#6]
@LeeBinder

Linux and MacOS don't show the app icon set in dotnet on the actual executable.

**Comment by dan0v** [comment]
Windows correctly sets the executable icon, as well as taskbar icons for open windows.

Linux does not set the executable icon correctly, but *does* show the correct icon for currently open windows.

How does MacOS behave? I don't have a Mac device to test unfortunately...

**Comment by LeeBinder** [comment]
with [xdelta3-cross-gui_1.0.1_macOS_x64-with-icon.zip](https://github.com/dan0v/xdelta3-cross-gui/files/5099241/xdelta3-cross-gui_1.0.1_macOS_x64-with-icon.zip) from [my comment](https://github.com/dan0v/xdelta3-cross-gui/issues/3#issuecomment-676687238):

![Screen Shot 2020-08-19 at 23 28 11](https://user-images.githubusercontent.com/39203497/90691517-b8564780-e273-11ea-82db-0c4176f1c157.jpg)

The icon can easily be set via paste the file info window in macOS (copied via clipboard from icon.png opened in the preview app):

![Screen Shot 2020-08-19 at 23 29 30](https://user-images.githubusercontent.com/39203497/90691602-df147e00-e273-11ea-988a-ce5aa647fad6.jpg)

**Comment by dan0v** [comment]
I appreciate you doing it by hand, but it's not really a solution to the underlying issue 😕 . The best would be some post-build process or script that could automatically set the icon correctly for Linux and Mac. If you / anybody finds a way to do something like that, please submit a PR.

**Comment by dan0v** [comment]
https://avaloniaui.net/docs/packing/macOS

macOS support is doable, I haven't found useful info for Linux though, as creating a .Desktop file won't work - only absolute file paths can be used to define icon locations.

**Comment by dan0v** [comment]
Resolved by 5c0b9ff6fa8074ddb39db9734d3930b79c2e8cd4 by bundling application to a macOS .app file. Icon now correctly displays, and it's also neater to have only 1 files to launch, as native macOS apps should. The macOS download under Releases has been updated to the new bundled filetype.

**Comment by LeeBinder** [comment]
Well done/ quickly solved & improved, @dan0v ! I am confirming xDelta3 Cross GUI.app displaying with the new icon, even in the dock.

**Comment by LeeBinder** [comment]
..just seeing that it's still showing up as 1.0:

![Screen Shot 2020-08-20 at 22 56 23](https://user-images.githubusercontent.com/39203497/90825113-c02bef80-e338-11ea-8ff3-c803af2a99a1.jpg)

That is easily adapted in `xDelta3 Cross GUI.app/Contents/Info.plist`:

![Screen Shot 2020-08-20 at 23 04 43](https://user-images.githubusercontent.com/39203497/90825829-c7073200-e339-11ea-9fa8-179adcf554a7.jpg)

save, touch ->
![Screen Shot 2020-08-20 at 23 07 55](https://user-images.githubusercontent.com/39203497/90826062-21a08e00-e33a-11ea-9cca-4047f3177625.jpg)
